/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmsys.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author राधे~राधे !
 */
public class RoomBook extends javax.swing.JFrame {
 Connection con;
  Statement st;
  ResultSet rs;
  String cid="";
String avail="Available";
    /**
     * Creates new form RoomBook
     */
    public RoomBook() {
        initComponents();
        connect();
        fetchid();
        fetchcustid();
        fetchRoomid();
//        SimpleDateFormat formatter=new SimpleDateFormat("dd MMM, yyyy");
//        Date date=new Date();
//        System.out.println(formatter.format(date));
    }
    
       public void connect()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/hmsys","root","");
            st = con.createStatement();
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this,""+e);
        }
    }
    public void fetchid(){
     try
       {
               int i=0;
                 ResultSet   rs=st.executeQuery("select reservid from roombook");
                    while(rs.next())
                    {
                        jComboBox1.addItem(rs.getString(1).toString());
                         i++; 
                    }
                    i++;
                    cid=Integer.toString(i);
                    jTextField1.setText(cid);
                }  catch(Exception e)
                {
                      JOptionPane.showMessageDialog(this,e);
                }
    }
     public void fetchcustid(){
     try
           {
               jComboBox2.removeAllItems();
               jComboBox2.addItem("Select");
               ResultSet   rs=st.executeQuery("select custid from customer");
                    while(rs.next())
                    {
                        jComboBox2.addItem(rs.getString(1).toString());
                    }
                }  catch(Exception e)
                {
                      JOptionPane.showMessageDialog(this,e);
                }
    }
    public void fetchRoomid(){
     try
           {
               jComboBox4.removeAllItems();
               jComboBox4.addItem("Select");
               ResultSet   rs=st.executeQuery("select rid from room where rstatus='"+avail+"'");
                    while(rs.next())
                    {
                        jComboBox4.addItem(rs.getString("rid").toString());
                    }
                }  catch(Exception e)
                {
                      JOptionPane.showMessageDialog(this,"fetchRoomid "+e);
                }
    }
public void clearField(){
   jComboBox1.removeAllItems();
   jComboBox1.addItem("Select");
   fetchid();
   jTextField2.setText("");
   jTextField3.setText("");
   jTextField4.setText("");
   jTextField5.setText("");
   jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField11.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jTextField10.setText("");
    jComboBox4.setSelectedIndex(0);
    jComboBox5.setSelectedIndex(0);
    jComboBox6.setSelectedIndex(0);
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Booking Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room Reservation ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 0, 10, new java.awt.Color(255, 0, 204)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Reservation ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Customer ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Firsrt Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 90, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Middle Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 137, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 200, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField5.setText("0");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Room Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Room Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Room ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Extra Bed Charges(Rs)");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 200, -1));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Book");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 70, 40));

        jButton2.setBackground(new java.awt.Color(255, 153, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Update");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 90, 40));

        jButton3.setBackground(new java.awt.Color(255, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 80, 40));

        jButton4.setBackground(new java.awt.Color(255, 153, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Booking List");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 130, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Extra Bed");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 140, -1));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField7.setText("0");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Total Charges");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 130, 20));

        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 130, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText(" From");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("To");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 30, -1));

        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 130, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Room Charges");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 130, 20));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField8.setText("0");
        jTextField8.setToolTipText("");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 140, -1));

        jButton5.setBackground(new java.awt.Color(255, 153, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Cancel");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 80, 40));

        jButton6.setBackground(new java.awt.Color(255, 153, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("<<");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 60, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Room Booking Status");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 180, -1));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Reserved" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 170, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Search");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, -1));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 200, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 160, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 100, -1));

        jLabel2.setBackground(new java.awt.Color(0, 255, 102));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(204, 0, 204)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Code for Room Booking.
        String id = jTextField1.getText();
        String custid = jComboBox2.getSelectedItem().toString();
        String fname = jTextField9.getText();
        String mname = jTextField2.getText();
        String lname = jTextField3.getText();
        String mobno = jTextField4.getText();
        
//        String rid = jComboBox4.getSelectedItem().toString();
        String rid = jTextField11.getText();
        String rtype = jTextField10.getText();
        String rnum = jTextField6.getText();
        String fdate = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String tdate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String rcharges = jTextField8.getText();
        String ebed = jComboBox5.getSelectedItem().toString();
        String ebcharges = jTextField5.getText();
        String tcharges = jTextField7.getText();
        String rstatus = jComboBox6.getSelectedItem().toString();
        
//        String dob =((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        
    SimpleDateFormat formatter=new SimpleDateFormat("dd MMM, yyyy");
    Date date=new Date();
   String bdate=formatter.format(date);
    try{
          if(id.equals("")||custid.equals("Select")||rtype.equals("Select")||rid.equals("Select")||fdate.equals("")||tdate.equals("")||rcharges.equals("")||ebed.equals("Select")||ebcharges.equals("")||rstatus.equals("Select")){
             JOptionPane.showMessageDialog(this,"Some Field is Empty","",JOptionPane.INFORMATION_MESSAGE);         
          }else{          
            String sql = "insert into roombook values('"+id+"','"+custid+"','"+fname+"','"+mname+"','"+lname+"','"+mobno+"','"+rid+"','"+rnum+"','"+rtype+"','"+fdate+"','"+tdate+"','"+rcharges+"','"+ebed+"','"+ebcharges+"','"+tcharges+"','"+rstatus+"','"+bdate+"')";
            st.executeUpdate(sql);
            
            String sql1 = "update room set rstatus='"+rstatus+"' where rid='"+rid+"'";
            PreparedStatement pst =con.prepareStatement(sql1);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Room Booking Successfully","",JOptionPane.INFORMATION_MESSAGE);
            
            clearField();
          }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Room ID Already Exist for Add");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new HomePage().show();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new BookingList().show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
//        Code For Search Customer Data from Customer Table
 int a=jComboBox2.getSelectedIndex();
        try{
            if(jComboBox2.getSelectedIndex()==0){
                jTextField9.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }else
            {
            
                 rs=st.executeQuery("select * from customer where custid='"+a+"'");
                 if(rs.next()==true)
                    {
                        jTextField9.setText(rs.getString("fname"));
                        jTextField2.setText(rs.getString("mname"));
                        jTextField3.setText(rs.getString("lname"));
                        jTextField4.setText(rs.getString("mobno"));
                    }
        }   
            }catch(Exception e)
                 {
                 JOptionPane.showMessageDialog(this, e);
                }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // Code for Roomid Data Fetch
        try
           {
                String a = jComboBox4.getSelectedItem().toString();
                if(a.equals("Select")){
                    jTextField6.setText("");
                    jTextField10.setText("");
                    jTextField11.setText("");
                }else                
                { 
                     rs=st.executeQuery("select * from room where rid='"+a+"' and rstatus='"+avail+"'");
                     if(rs.next()==true)
                        {
                            jTextField6.setText(rs.getString("rnum"));
                            jTextField10.setText(rs.getString("rtype"));
                            jTextField11.setText(rs.getString("rid"));
                        }
                }   
            }catch(Exception e)
            {
//                JOptionPane.showMessageDialog(this,"jCOmbo4 "+ e);
            }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        calculate();                
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
          calculate();
    }//GEN-LAST:event_jTextField5KeyReleased
public void calculate()
{
       try{
        String rcharges=jTextField8.getText();
        String ebcharges=jTextField5.getText();
        float rc =Float.parseFloat(rcharges),ebc=Float.parseFloat(ebcharges),total=0;
        
           total = rc + ebc;
          jTextField7.setText(Float.toString(total));
        }
        catch(Exception e){
           jTextField7.setText("0.0");
        }
}

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
char c=evt.getKeyChar();
         String no=jTextField8.getText();
        int len=no.length();
        if(Character.isDigit(c))
        {
            if(len<10)
            {
                jTextField8.setEditable(true);
            }
            else 
            {
                jTextField8.setEditable(false);
            }
        }else 
        {
            if(Character.isWhitespace(c)||Character.isISOControl(c))
            jTextField8.setEditable(true);
            else
            jTextField8.setEditable(false);
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

//        int a=jComboBox1.getSelectedIndex();
//        try{
//            if(jComboBox1.getSelectedIndex()==0){
//             clearField();
//            }else
//            {
//                 rs=st.executeQuery("select * from customer where custid='"+a+"'");
//                 if(rs.next()==true)
//                    {
//                        jTextField7.setText(rs.getString(1));
//                        jTextField1.setText(rs.getString(2));
//                        jTextField2.setText(rs.getString(3));
//                        jTextField3.setText(rs.getString(4));
//                        jTextField4.setText(rs.getString(5));
//                        jTextField8.setText(rs.getString(6));
//                        jTextField5.setText(rs.getString(7));
//                        jComboBox2.setSelectedItem(rs.getString(8));
//                        jTextField6.setText(rs.getString(9));
//                    }
//        }   
//            }catch(Exception e)
//                 {
//                 JOptionPane.showMessageDialog(this, e);
//                }
//



                int a=jComboBox1.getSelectedIndex();
        try{
            if(jComboBox1.getSelectedIndex()==0){
             clearField();
            }else
            {
                  
                 ResultSet rs=st.executeQuery("select reservid,rtype,rid,rnum,fromdate,todate,rcharges,ebed,ebcharges,tcharges,rstatus,cid from roombook where reservid='"+a+"'");
                 if(rs.next()==true)
                    {
                    jTextField1.setText(rs.getString("reservid"));
//                    jTextField9.setText(rs.getString("fname"));
//                    jTextField2.setText(rs.getString("mname"));
//                    jTextField3.setText(rs.getString("lname"));
//                    jTextField4.setText(rs.getString("mobno"));

                    jTextField10.setText(rs.getString("rtype"));
                    jTextField11.setText(rs.getString("rid"));
//                    jComboBox4.setSelectedItem(rs.getString("rid"));
                     jTextField6.setText(rs.getString("rnum"));
                    ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(rs.getString("fromdate"));
                    ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(rs.getString("todate"));
                    jTextField8.setText(rs.getString("rcharges"));
                    jComboBox5.setSelectedItem(rs.getString("ebed"));
                    jTextField5.setText(rs.getString("ebcharges"));
                    jTextField7.setText(rs.getString("tcharges"));
                    jComboBox6.setSelectedItem(rs.getString("rstatus"));
                    jComboBox2.setSelectedItem(rs.getString("cid"));
                    }
        }   
            }catch(Exception e)
                 {
                 JOptionPane.showMessageDialog(this, e);
                }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Code for Update Booking 
        String id = jTextField1.getText();
        String custid = jComboBox2.getSelectedItem().toString();
        String fname = jTextField9.getText();
        String mname = jTextField2.getText();
        String lname = jTextField3.getText();
        String mobno = jTextField4.getText();
        
        String rid = jTextField11.getText();
        String rtype = jTextField10.getText();
        String rnum = jTextField6.getText();
        String fdate = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String tdate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String rcharges = jTextField8.getText();
        String ebed = jComboBox5.getSelectedItem().toString();
        String ebcharges = jTextField5.getText();
        String tcharges = jTextField7.getText();
        String rstatus = jComboBox6.getSelectedItem().toString();
        
        SimpleDateFormat formatter=new SimpleDateFormat("dd MMM, yyyy");
        Date date=new Date();
        String bdate=formatter.format(date);
        String check="";
        try{
            rs=st.executeQuery("select * from roombook where reservid='"+id+"'");
            if(rs.next()==true){
             check=rs.getString(1);
            }
            else{
                JOptionPane.showMessageDialog(this,"Room Booking ID not Exist for Update","",JOptionPane.INFORMATION_MESSAGE);         
            }
           if(check.equals(id))
           {
            if(id.equals("")||custid.equals("Select")||rtype.equals("")||rid.equals("")||rnum.equals("")||fdate.equals("")||tdate.equals("")||rcharges.equals("")||ebed.equals("Select")||ebcharges.equals("")||rstatus.equals("Select")){
             JOptionPane.showMessageDialog(this,"Some Field is Empty","",JOptionPane.INFORMATION_MESSAGE);         
            }else{ 
                String sql = "update roombook set reservid='"+id+"',cid='"+custid+"',fname='"+fname+"',mname='"+mname+"',lname='"+lname+"',mobno='"+mobno+"',rid='"+rid+"',rnum='"+rnum+"',rtype='"+rtype+"',fromdate='"+fdate+"',todate='"+tdate+"',rcharges='"+rcharges+"',ebed='"+ebed+"',ebcharges='"+ebcharges+"',tcharges='"+tcharges+"',rstatus='"+rstatus+"',bdate='"+bdate+"' where reservid='"+id+"'";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.executeUpdate();

                String sql1 = "update room set rstatus='"+rstatus+"' where rid='"+rid+"'";
                PreparedStatement pst1 =con.prepareStatement(sql1);
                pst1.executeUpdate();

                JOptionPane.showMessageDialog(this,"Room Booking Update Successfully","",JOptionPane.INFORMATION_MESSAGE);

                clearField();
            }
           }
          }catch(Exception e){
      JOptionPane.showMessageDialog(this,"Room ID not found"+e);
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();
        String custid = jComboBox2.getSelectedItem().toString();
        String fname = jTextField9.getText();
        String mname = jTextField2.getText();
        String lname = jTextField3.getText();
        String mobno = jTextField4.getText();
        
        String rid = jTextField11.getText();
        String rtype = jTextField10.getText();
        String rnum = jTextField6.getText();
        String fdate = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String tdate = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String rcharges = jTextField8.getText();
        String ebed = jComboBox5.getSelectedItem().toString();
        String ebcharges = jTextField5.getText();
        String tcharges = jTextField7.getText();
        String rstatus = jComboBox6.getSelectedItem().toString();
        
        SimpleDateFormat formatter=new SimpleDateFormat("dd MMM, yyyy");
        Date date=new Date();
        String bdate=formatter.format(date);
        String check="";
        try{
          rs=st.executeQuery("select * from roombook where reservid='"+id+"'");
          if(rs.next()==true){
             check=rs.getString(1);
          }
          else{
            JOptionPane.showMessageDialog(this,"Room Booking Details not found for delete","",JOptionPane.INFORMATION_MESSAGE);         
            }
         if(check.equals(id)){
             if(id.equals("")||custid.equals("Select")||rtype.equals("")||rid.equals("")||rnum.equals("")||fdate.equals("")||tdate.equals("")||rcharges.equals("")||ebed.equals("Select")||ebcharges.equals("")||rstatus.equals("Select")){
             JOptionPane.showMessageDialog(this,"Some Field is Empty","",JOptionPane.INFORMATION_MESSAGE);         
            }
             else
             { 
                int confirm = JOptionPane.showConfirmDialog(this,"Are You Really want to delete record","Confirm",JOptionPane.YES_NO_OPTION);
                if(confirm==0){
                String sql = "delete from roombook where reservid='"+id+"'";
                PreparedStatement pst =con.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Room Booking Delete Successfully","",JOptionPane.INFORMATION_MESSAGE);
                clearField();
                 }
            }
         }
          }catch(Exception e){
      JOptionPane.showMessageDialog(this,"Room Booking ID not found");
    }

    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
